name: RconServer
main: pmofficial\RconServer\Main
version: 1.0.0
api: 4.0.0
load: POSTWORLD
author: pmofficial
description: Allow RCON clients to control your server
website: https://github.com/pmmp/RconServer
